//
// Created by 地铁DXTL on 2023/12/26.
//

#ifndef LIBRARY_BOOK_MANAGER_CONSTANT_DEFINITIONS_H
#define LIBRARY_BOOK_MANAGER_CONSTANT_DEFINITIONS_H

#define Status int

#endif //LIBRARY_BOOK_MANAGER_CONSTANT_DEFINITIONS_H
